parameters:
    krg.shipping.form.type.class: KRG\ShippingBundle\Form\Type\ShippingType

services:
    krg.shipping.registry:
        class: KRG\ShippingBundle\Transport\TransportRegistry
        calls:
            - [setContainer, [@service_container]]

    krg.shipping.form.type:
        class: %krg.shipping.form.type.class%
        arguments: [%krg.shipping.shipping_class%]
        tags:
            - {name: form.type, alias: shipping}
